-- load plugins
require('plugins.statusline')

-- -- configure nvim-bufferline
-- vim.opt.termguicolors = true
-- require('bufferline').setup{
--   options = {
--     numbers = 'none',
--     separator_style = 'thin',
--     always_show_bufferline = true,
--     offsets = {
--       -- {
--       --   filetype = 'nerdtree',
--       --   text = 'NERDTree',
--       --   text_align = 'center',
--       -- },
--       {
--         filetype = 'NvimTree',
--         text = 'NvimTree',
--         text_align = 'center',
--       }
--     }
--   }
-- }
